src/components/viz/histogram/TimestampHistogram.svelte, src/dataAPI/ProfileModel.ts, src/stores.ts
Working temporal profiling chart
Fixes #15
=> Working profile chart for timestamps

src/components/ColumnEntry.svelte, src/components/viz/TopKSummary.svelte
Can select values in the top k summary
Fixes #13
=> allow selecting text in summary of categorical cols

src/dataAPI/ProfileModel.ts
Add better comments explaining things
Fixes #19
=> add better comments

src/components/viz/histogram/TimestampHistogram.svelte
Fixes text wrapping by removing columns and unused estimated smallest timegrain from timeline view
Fixes #22
=> fix text wrap for date span

src/components/ColumnEntry.svelte, src/components/ColumnProfile.svelte, src/stores.ts
- Highlight columns of same name on hover with gray background across dataframe profiles
Fixes #27
=> highlight same names on hover

src/components/ColumnEntry.svelte
fix styles on column profile hover where was staying highlight active after leave
=> style fix for column hover

src/common/exchangeInterfaces.ts, src/components/ColumnProfile.svelte, src/components/actions/outline.ts, src/components/actions/scrub-action-factory.ts, src/components/utils/constants.ts, src/components/utils/formatters.ts, src/components/viz/histogram/TimestampHistogram.svelte, src/components/viz/timestamp/TimestampBound.svelte, src/components/viz/timestamp/TimestampDetail.svelte, src/components/viz/timestamp/TimestampMouseoverAnnotation.svelte, src/components/viz/timestamp/TimestampPaths.svelte, src/components/viz/timestamp/TimestampProfileSummary.svelte, src/components/viz/timestamp/TimestampTooltipContent.svelte, src/components/viz/timestamp/ZoomWindow.svelte, src/components/viz/timestamp/extremum-resolution-store.ts, src/components/viz/timestamp/utils.ts, src/dataAPI/ProfileModel.ts, src/stores.ts
- Update to recent rill version of timestamp vis
- Note: we are not rolling up timestamps in quite the same way they are; I am just binning into a large number of bins and then using the auto generated bin edges for the rollup 
Fixes #23
=> add new timestamp viz with zooming

src/components/actions/scrub-action-factory.ts, src/components/viz/timestamp/TimestampDetail.svelte, src/dataAPI/ProfileModel.ts
- Incorporate fix from rill for zooming bug with plot bounds
https://github.com/rilldata/rill-developer/pull/995
=> fix bug with zoom bounds

src/components/ColumnProfile.svelte, src/components/viz/BarAndLabel.svelte
=> use grey for nulls background

src/components/ColumnProfile.svelte, src/components/DFProfile.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Better defaults for empty dataframe with no cols or rows
- with no rows
Fixes #41, #39
=> Error handling

MANIFEST.in
=> exclude .vscode from manifest to pass build check in PR

src/dataAPI/ProfileModel.ts
Update the name of the connected notebook when renamed
Fixes #40
=> update notebook name when renamed

src/components/DFProfile.svelte, src/components/Profiler.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Adds new feature to indicate if the dataframe is in the current cell
- Addresses #43
=> Focus indicator for code in current cell

examples/SF Housing Demo.ipynb, examples/df_housing_sample.csv
Adds example notebook for binder
=> add example notebook

.github/workflows/build.yml, MANIFEST.in, README.md, package.json
=> Fix build checks and update readme and version

CONTRIBUTING.md, digautoprofiler/__init__.py, digautoprofiler/profile_lib.py, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Refactor to have pandas manipulation functions as utils in digautoprofiler
- Will allow for more complex python code to be executed in the future
Fixes #2
=> move pandas manipulation functions to python file in digautoprofiler

src/components/actions/scrub-action-factory.ts, src/components/viz/timestamp/TimestampDetail.svelte
- Fixes bug where releasing datetime zoom past window bound does not zoom
Fixes #64
=> move event listener for scrub end to window

src/components/DFProfile.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts, src/dataAPI/jupyter/cell.ts, src/dataAPI/jupyter/notebook.ts
=> Show output from current cell as df and hide all other variables with underscores

digautoprofiler/profile_lib.py, src/common/exchangeInterfaces.ts, src/components/DFProfile.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Warn if a dataframe has multiple columns with same name and do not display them (causes errors when making selections in other code)
Fixes #101
=> 101 duplicate cols

digautoprofiler/profile_lib.py, src/common/exchangeInterfaces.ts, src/components/ColumnProfile.svelte, src/components/viz/categorical/StringStats.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Show min, max, and average length of strings (in chars) for cat columns
Fixes #99
=> String length stats for cat columns

src/components/ColumnProfile.svelte, src/components/export-code/ExportChartButton.svelte, src/components/export-code/ExportableCode.ts, src/components/viz/histogram/NumericHistogram.svelte, src/components/viz/histogram/SummaryStatLabel.svelte, src/dataAPI/ProfileModel.ts
- Option click on summary stat to export to code
Fixes #100
=> export selections to nb from numeric histogram

src/components/export-code/ExportChartButton.svelte, src/components/icons/ExportIcon.svelte, src/components/viz/histogram/NumericHistogram.svelte, src/components/viz/histogram/SummaryStatLabel.svelte
- Use same export button to export summary stats
=> standard export button

digautoprofiler/profile_lib.py, digautoprofiler/utils.py, src/common/exchangeInterfaces.ts, src/components/ColumnProfile.svelte, src/components/DFProfile.svelte, src/components/data-types/pandas-data-types.ts, src/components/fact-panel/VizOrStats.svelte, src/dataAPI/ProfileModel.ts, src/dataAPI/jupyter/PythonExecutor.ts
- Consolidate requests to make fewer kernel calls
- Should improve performance since making half as many calls as before
=> Refactor comm

src/components/export-code/ExportableCode.ts, src/components/fact-panel/VizOrStats.svelte, src/components/viz/TopKSummary.svelte, src/components/viz/histogram/HistogramBase.svelte, src/components/viz/histogram/NumericHistogram.svelte, src/components/viz/histogram/histogram-tooltip/HistogramTooltip.svelte
- Export single bin from histogram or single category from top k chart
=> can export single quant bin or single category with option click

src/components/export-code/ExportChartButton.svelte, src/components/export-code/ExportFactButton.svelte, src/components/viz/TopKSummary.svelte, src/components/viz/histogram/HistogramBase.svelte, src/components/viz/histogram/SummaryStatLabel.svelte
=> better logs

CONTRIBUTING.md, digautoprofiler/__init__.py, digautoprofiler/handlers.py, digautoprofiler/logger.py, jupyter-config/nb-config/digautoprofiler.json, jupyter-config/server-config/digautoprofiler.json, package-lock.json, package.json, setup.py, src/ProfilePanel.ts, src/components/ColumnEntry.svelte, src/components/DFProfile.svelte, src/components/export-code/ExportChartButton.svelte, src/components/export-code/ExportFactButton.svelte, src/components/viz/TopKSummary.svelte, src/components/viz/histogram/HistogramBase.svelte, src/components/viz/histogram/SummaryStatLabel.svelte, src/dataAPI/ProfileModel.ts, src/logger/Logger.ts, src/logger/guid.ts, tsconfig.json
- Writes logs to `~/.autoprofiler/autoprofiler.log`
- Preaggregates interaction traces so no data identity information is stored
=> Improved, anonymous logger to local file

src/components/Profiler.svelte
format issue link to be aligned
=> fix alignment in issue link

digautoprofiler/profile_lib.py
=> set correct curr len default

README.md, package-lock.json, package.json, requirements.txt
Pin jupyterlab version to jupyter v3
=> pin to jl v3
